spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: ${DOCKER_IP}:9200
  redis:
    #    url: redis://${REDIS_URL}
    topic: meetingEventQueue
    host: ${DOCKER_IP}
    port: 6379
  elasticsearch:
    rest:
      uris: ${DOCKER_IP}:9200

server:
  port: 8083