spring:
  data:
    mongodb:
      uri: mongodb://${DOCKER_IP}:27017/meeting
  redis:
    url: redis://${DOCKER_IP}:6379
    topic: meetingEventQueue

server:
  port: 8082

searchservice:
  api:
    url: "http://localhost:8083/api/events"
    index: "/index"
